- name: enabled logstash
  service:
    name: "logstash"
    enabled: true
    daemon_reload: True
    state: restarted
  when: is_logstash_enabled == 1


- name: enabled filebeat
  service:
    name: "filebeat"
    enabled: true
    daemon_reload: True
    state: restarted
  when: is_filebeat_enabled == 1

- name: restart logstash
  service:
    name: "logstash"
    state: restarted
  when: is_logstash_enabled == 1

- name: restart filebeat
  service:
    name: "filebeat"
    state: restarted
    enabled: true
  when: is_filebeat_enabled == 1