# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.define "s01" do |server|
    server.vm.box = "Ubuntu-20.04"
    server.vm.hostname="s01"
    server.vm.network "private_network", ip: "10.0.3.41"
    server.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
    server.vm.network "forwarded_port", guest: 22, host: (63041)
    server.vm.provider "virtualbox" do |v|
        v.name = "s01"
        v.memory = 4096
        v.cpus = 2
    end
    server.vm.provision "shell", inline: <<-SHELL
        echo "Created."
    SHELL
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yaml"
  end
  
end
